
FROM oven/bun:alpine

WORKDIR /apps/web

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages

COPY ./apps/app/package.json ./web/package.json
COPY ./apps/app/bun.lock ./web/bun.lock

RUN bun install

COPY ./apps/app ./web

RUN bun run docker:database

CMD [ "bun","run","docker:web" ]