
FROM oven/bun:alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/wss/package.json ./apps/wss/package.json

RUN bun install

COPY ./apps/wss ./apps/wss

EXPOSE 8080

CMD [ "bun","run","docker:wss" ]
