
FROM oven/bun:alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages

COPY ./apps/app/package.json ./apps/app/package.json

RUN bun install

COPY ./apps/app ./apps/app


CMD [ "bun","run","docker:nextJS" ]